### PR TITLE
Add "drive not recognized" to troubleshooting

### PR DESCRIPTION
**Pull request by rdswift**
### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

In some cases, Picard will not recognize an external drive.  This is discussed in https://tickets.metabrainz.org/browse/PICARD-2829

### Description of the Change

Add a page to the "Troubleshooting" section to deal with Picard not recognizing external drives.  Also add a warning to the "Allow selection of multiple directories" option setting.

### Additional Action Required

Once merged, the translation files will need to be updated.  Then it should be cherry picked into the "2.11" branch along with any translation updates.

### CODE REVIEW

**Comment by rdswift** [comment]
Updated the warning text to match that displayed within Picard.  See https://github.com/metabrainz/picard/pull/2364.

**Review by phw — COMMENTED** [review]
I'd probably not add this FAQ entry anymore at all now that we have https://github.com/metabrainz/picard/pull/2365 . What do you think?

Only add the warning section to the options doc

**Comment by rdswift** [comment]
> I'd probably not add this FAQ entry anymore at all now that we have [metabrainz/picard#2365](https://github.com/metabrainz/picard/pull/2365) . What do you think?

Agreed.  I'll submit the changes.

**Review by phw — APPROVED** [review]
Let's merge that

**Pull request merged**
