### PR TITLE
Embed video tutorials into corresponding doc pages

### PR DESCRIPTION
**Pull request by phw**
### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Description of the Change

This change embeds tutorial videos from the MetaBrainz Youtube channel that aerozol recently made. This can help users who prefer the visual guidance through the program over the textual description.

The following videos are embedded on the relevant pages:

- What is MusicBrainz Picard
- How to add a DiscID to MusicBrainz
- What are AcoustIDs and how to submit them

The videos are embedded using the [`sphinxcontrib.youtube`](https://github.com/sphinx-contrib/youtube) module.

### Additional Action Required

I set the `:privacy_mode:` flag for embedding the videos. This is supposed to load the videos via youtube-nocookie.com to avoid the Google cookies. However, in my tests this did currently not work as intended, see https://github.com/sphinx-contrib/youtube/issues/57

### CODE REVIEW

**Comment by phw** [comment]
This is a screenshot on how this looks like on the AcoustId submission docs:

grafik

**Comment by phw** [comment]
> The only thing that wonder is if it is worth adding some sort of indicator to the section title in the left hand column indicating that the tutorial also provides a video option?

Generally I think making this more clear is a good idea. Not sure about the icon, though. I think it might give the false impression that this is only about a video tutorial, but actually the primary tutorial is still the text. The video is kind of additional.

Maybe we could add a separate section "Video tutorials" that just provide a list of the available videos?

**Comment by rdswift** [comment]
> Maybe we could add a separate section "Video tutorials" that just provide a list of the available videos?

That suggestion makes a lot of sense to me.  It gives the available videos more visibility, without making it confusing.  If you like, I can take a first look at it.

**Comment by phw** [comment]
That would be great. I'm not quite sure how to bed present this. A list of links? Or directly the embedded videos again? Probably needs some experimentation.

**Pull request merged**
